### ISSUE TITLE
Parse URL with double forward slashes (//) in path

### ISSUE THREAD

**Issue by ivo-urbanek** [seznam/IMA.js-server#12]
Bug with parsing URLs like:
http://local.domain.cz/?service=http://www.seznam.cz/hledej/alice
http://local.domain.test/img//big/90/3916290_1.jpg
http://local.inzeraty.test/img//big/90/3916290_1.jpg?redirect=http://favorite.baradios.cz/radios/ggg/listen

**Comment by mjancarik** [comment]
merged https://github.com/seznam/IMA.js-server/pull/13
